/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Prueba.Tecnica.Chourcair.T;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
